spring:
  application:
    name: carrito-service
  cloud:
    circuitbreaker:
      resilience4j:
        enable-auto-configuration: true
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.MySQL8Dialect
  datasource:
    url: ${DATASOURCE_URL}
    username: ${DATASOURCE_ROOT}
    password: ${DATASOURCE_PASS}
    driver-class-name: com.mysql.cj.jdbc.Driver
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: ${JWK_SET_URI}
    client:
      registration:
        keycloak:
          client-id: ${CLIENT_ID}          # <-- el ID de tu cliente en Keycloak
          client-secret: ${CLIENT_SECRET}
          scope: openid,profile,email
          authorization-grant-type: authorization_code
          redirect-uri: "{baseUrl}/login/oauth2/code/keycloak"
      provider:
        keycloak:
          issuer-uri: ${ISSUES_URI}

server:
  port: 8082

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_DEFAULTZONE}
  instance:
    hostname: localhost
    prefer-ip-address: true
    ip-address: 127.0.0.1
    instance-id: ${spring.application.name}:${server.port}
