version: '3'
services:
  carrito-service:
    container_name: carrito-service
    image: mysql:8.0.33
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: carrito-service
      MYSQL_USER: uncledave
      MYSQL_PASSWORD: Test123
      MYSQL_ROOT_PASSWORD: root
    ports:
      - 3312:3306   # puerto externo 3307 -> interno 3306

  productos-service:
    container_name: productos-service
    image: mysql:8.0.33
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: productos-service
      MYSQL_USER: uncledave
      MYSQL_PASSWORD: Test123
      MYSQL_ROOT_PASSWORD: root
    ports:
      - 3308:3306   # puerto externo 3308 -> interno 3306

  stock-service:
    container_name: stock-service
    image: mysql:8.0.33
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: stock-service
      MYSQL_USER: uncledave
      MYSQL_PASSWORD: Test123
      MYSQL_ROOT_PASSWORD: root
    ports:
      - 3309:3306   # puerto externo 3309 -> interno 3306
#
#  ventas-service:
#    container_name: ventas-service
#    image: mysql:8.0.33
#    restart: unless-stopped
#    environment:
#      MYSQL_DATABASE: ventas-service
#      MYSQL_USER: uncledave
#      MYSQL_PASSWORD: Test123
#      MYSQL_ROOT_PASSWORD: root
#    ports:
#      - 3310:3306   # puerto externo 3310 -> interno 3306

  ### MySQL database for Keycloak
  db-keycloak:
    container_name: db-keycloak
    image: mysql:8.0.33
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: db_keycloak
      MYSQL_USER: uncledave
      MYSQL_PASSWORD: Test123
      MYSQL_ROOT_PASSWORD: root
    ports:
      - 3311:3306   # puerto externo 3311 -> interno 3306
    expose:
      - 3306

### Keycloak
  keycloak:
    container_name: keycloak
    image: quay.io/keycloak/keycloak:21.0.2
    command: ["start-dev"]          # modo dev (útil para pruebas locales)
    restart: unless-stopped
    depends_on:
      - db-keycloak
    ports:
      - "8181:8181"
    environment:
      # Base de datos (MySQL)
      KC_DB: mysql
      KC_DB_URL: jdbc:mysql://db-keycloak:3306/db_keycloak?useSSL=false&allowPublicKeyRetrieval=true&characterEncoding=UTF-8&serverTimezone=UTC
      KC_DB_USERNAME: uncledave
      KC_DB_PASSWORD: Test123

      # Admin user
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin

      # Puerto HTTP interno de Keycloak
      KC_HTTP_PORT: 8181
