spring:
  application:
    name: eureka-server
  security:
    user:
      name: eureka
      password: password

server:
  port: 8761

eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
  instance:
    hostname: localhost
